# Generated by Django 5.2 on 2025-05-19 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
    ]
